# Generated by Django 4.2.1 on 2023-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectM',
            fields=[
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
