# Generated by Django 4.2.1 on 2023-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlem',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titlem',
            name='vol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
